@BASE_URL= http://localhost:3000/api



GET {{BASE_URL}}/users
###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "isim": "Barış",
    "soyisim": "Uğur",
    "yas": 25
}
###
PATCH  {{BASE_URL}}/users/5f70a7165f07cd3c78910eda
Content-Type: application/json

{
    "isim": "m.barisugur",
    "yas": 24
}
###
DELETE {{BASE_URL}}/users/5f717b063094b630183c5b28
Content-Type: application/json

